apiVersion: v1
kind: ConfigMap 
metadata:
  name: cf-wordpress 
data:
  WORDPRESS_DB_HOST: svc-mysql
  WORDPRESS_DB_PASSOWRD: wordpress2020

--- 
apiVersion: v1
kind: ConfigMap 
metadata:
  name: cf-mysql 
data:
  MYSQL_ROOT_PASSWORD: wordpress2020