apiVersion: v1 
kind: Service 
metadata:
  name: svc-wordpress
spec:
  type: LoadBalancer
  selector:
    app: wordpress-deployment
  ports:
    - port: 80

---
apiVersion: v1 
kind: Service 
metadata:
  name: svc-mysql
spec:
  type: ClusterIP 
  selector:
    app: mysql-deployment
  ports:
    - port: 3306