apiVersion: apps/v1 
kind: Deployment 
metadata:
  name: wordpress-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress-deployment
  template:
    metadata:
      labels:
        app: wordpress-deployment
    spec:
      containers:
        - name: wordpress-image
          image: wordpress:latest
          resources:
            limits:
              memory: '500Mi'
              cpu: '500m'
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: cf-wordpress
          volumeMounts:
            - mountPath: /var/www/html/
              name: vol1
    volumes:
      - name: vol1 
        persistentVolumeClaim:
          claimName: pvc-wordpress
